apiVersion: v1
kind: ConfigMap
metadata:
  name: group-hexaglobe
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: group-hexaglobe
data:
  catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: hexaglobe
    spec:
      type: team
      profile:
        displayName: HexaGlobe
      children: []
